<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';


$client = new \Github\Client();

$client->authenticate('df24236dd9a1421f088ba839e0de061191009c45', null,Github\Client::AUTH_URL_TOKEN);
$repositories = $client->api('user')->repositories('Aurelie-feyzin');

$result=[];
$num = 0;
foreach($repositories as $repo) {

    $result[$num]['name'] = $repo['name'];
    $result[$num]['avatar'] = $repo['owner']['avatar_url'];
    $result[$num]['date'] = $repo['updated_at'];
    $num++;

}


return $result;
